title: Henning Støverud
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://blog.stoverud.no
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: henningst
   twitter: henningst
   facebook: henning.stoverud
   email: henning@stoverud.no

google_analytics: "UA-24835523-3"
