#
###################################
# Site wide configuration
####################################
#
title: Henning Støverud
email: henning@stoverud.no
description: My personal blog where I write about random tech stuff.
url: https://blog.stoverud.no # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /posts/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Henning Støverud
  avatar: henning.png
  job: "web developer"
  bio: "full stack developer, currently working at HR Manager Talent Solutions"
  email: henning@stoverud.no
  disqus-shortname: stoverudno
  twitter: henningst
  facebook: henning.stoverud
  google:
    plus: #username
    analytics: UA-24835523-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: henningst
  gitlab: #username
  stackoverflow: #5795/henningst   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: henningstoverud
  skype: #username
  xing: #username
  instagram: henningsto
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
