title: Henning Støverud
description: >
  **I am Strata**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP](http://html5up.net).
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: henningst
facebook_username: "henning.stoverud"
twitter_username: "henningst"
linkedin_username: "henningstoverud"
instagram_username: "henningsto"
pinterest_username:
flickr_username:
github_username:  "henningst"
feed_icon: rss
email: "henning@stoverud.no"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
