title: Henning Støverud
description: Henning Støverud's blog where I write about random tech stuff.

url: http://blog.stoverud.no
baseurl: ""
paginate_path: "/posts/page:num/"
permalink: /posts/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-sitemap]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: henningst
   twitter: henningst
   facebook: henning.stoverud
   email: henning@stoverud.no

google_analytics: "UA-24835523-3"
